apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "overleash.fullname" . }}-configmap
  namespace: {{ include "overleash.namespace" . | quote }}
  labels:
    {{- include "overleash.labels" . | nindent 4 }}
data:
{{ toYaml .Values.extraEnv | indent 2 }}
