{{- if .Values.metrics.enabled }}
{{- if .Values.metrics.service }}
{{- if (.Values.metrics.service).enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "overleash.fullname" . }}-metrics
  namespace: {{ include "overleash.namespace" . | quote }}
  labels:
    {{- include "overleash.labels" . | nindent 4 }}
    {{- with .Values.metrics.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.metrics.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "overleash.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}