{{- if not .Values.sidecar.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "overleash.fullname" . }}
  namespace: {{ include "overleash.namespace" . | quote }}
  labels:
    {{- include "overleash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "overleash.selectorLabels" . | nindent 4 }}
{{end}}
