// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: context.proto

package unleashengine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	SessionId     *string                `protobuf:"bytes,2,opt,name=sessionId,proto3,oneof" json:"sessionId,omitempty"`
	Environment   *string                `protobuf:"bytes,3,opt,name=environment,proto3,oneof" json:"environment,omitempty"`
	AppName       *string                `protobuf:"bytes,4,opt,name=appName,proto3,oneof" json:"appName,omitempty"`
	CurrentTime   *string                `protobuf:"bytes,5,opt,name=currentTime,proto3,oneof" json:"currentTime,omitempty"`
	RemoteAddress *string                `protobuf:"bytes,6,opt,name=remoteAddress,proto3,oneof" json:"remoteAddress,omitempty"`
	// Note: Protobuf maps are generated as non-pointers in Go.
	// To get a pointer to a map in Go, you would need a wrapper,
	// but usually, an empty map is preferred in Go/Proto logic.
	Properties    map[string]string `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Context) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *Context) GetEnvironment() string {
	if x != nil && x.Environment != nil {
		return *x.Environment
	}
	return ""
}

func (x *Context) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	return ""
}

func (x *Context) GetCurrentTime() string {
	if x != nil && x.CurrentTime != nil {
		return *x.CurrentTime
	}
	return ""
}

func (x *Context) GetRemoteAddress() string {
	if x != nil && x.RemoteAddress != nil {
		return *x.RemoteAddress
	}
	return ""
}

func (x *Context) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_context_proto protoreflect.FileDescriptor

const file_context_proto_rawDesc = "" +
	"\n" +
	"\rcontext.proto\x12\runleashengine\"\xbf\x03\n" +
	"\aContext\x12\x1b\n" +
	"\x06userId\x18\x01 \x01(\tH\x00R\x06userId\x88\x01\x01\x12!\n" +
	"\tsessionId\x18\x02 \x01(\tH\x01R\tsessionId\x88\x01\x01\x12%\n" +
	"\venvironment\x18\x03 \x01(\tH\x02R\venvironment\x88\x01\x01\x12\x1d\n" +
	"\aappName\x18\x04 \x01(\tH\x03R\aappName\x88\x01\x01\x12%\n" +
	"\vcurrentTime\x18\x05 \x01(\tH\x04R\vcurrentTime\x88\x01\x01\x12)\n" +
	"\rremoteAddress\x18\x06 \x01(\tH\x05R\rremoteAddress\x88\x01\x01\x12F\n" +
	"\n" +
	"properties\x18\a \x03(\v2&.unleashengine.Context.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_userIdB\f\n" +
	"\n" +
	"_sessionIdB\x0e\n" +
	"\f_environmentB\n" +
	"\n" +
	"\b_appNameB\x0e\n" +
	"\f_currentTimeB\x10\n" +
	"\x0e_remoteAddressB\x11Z\x0f./unleashengineb\x06proto3"

var (
	file_context_proto_rawDescOnce sync.Once
	file_context_proto_rawDescData []byte
)

func file_context_proto_rawDescGZIP() []byte {
	file_context_proto_rawDescOnce.Do(func() {
		file_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)))
	})
	return file_context_proto_rawDescData
}

var file_context_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_context_proto_goTypes = []any{
	(*Context)(nil), // 0: unleashengine.Context
	nil,             // 1: unleashengine.Context.PropertiesEntry
}
var file_context_proto_depIdxs = []int32{
	1, // 0: unleashengine.Context.properties:type_name -> unleashengine.Context.PropertiesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_context_proto_init() }
func file_context_proto_init() {
	if File_context_proto != nil {
		return
	}
	file_context_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_context_proto_goTypes,
		DependencyIndexes: file_context_proto_depIdxs,
		MessageInfos:      file_context_proto_msgTypes,
	}.Build()
	File_context_proto = out.File
	file_context_proto_goTypes = nil
	file_context_proto_depIdxs = nil
}
