/* Generated by cbindgen from the frontendengine crate. Do not edit by hand.
 *
 * Memory ownership:
 *   new_engine()            -> free_engine()
 *   take_state()            -> free_response()
 *   resolve(), resolve_all() -> free_rust_buffer(ptr, len)
 *
 * resolve() and resolve_all() return NULL and write 0 to out_len on failure.
 */


#ifndef FRONTEND_ENGINE_H
#define FRONTEND_ENGINE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

void *new_engine(void);

/**
 * # Safety
 * `engine_ptr` must be null, or a pointer returned by [`new_engine`] that has
 * not already been freed. Must not be called concurrently with any other call
 * using the same pointer.
 */
void free_engine(void *engine_ptr);

/**
 * Replaces the engine's toggle state from a JSON `UpdateMessage`.
 *
 * Always returns a non-null JSON [`Response`], which the caller must release
 * with [`free_response`].
 *
 * # Safety
 * `engine_ptr` must be null or from [`new_engine`]; `json_ptr` must be null or
 * a valid NUL-terminated C string that stays alive for the call.
 */
const char *take_state(void *engine_ptr, const char *json_ptr);

/**
 * Evaluates every known toggle.
 *
 * On success returns a `EvaluatedToggleList` protobuf and writes its length to
 * `out_len`; the buffer must be released with [`free_rust_buffer`]. On failure
 * returns null and writes `0`.
 *
 * # Safety
 * `engine_ptr` must be null or from [`new_engine`]. `context_data` must be
 * readable for `context_len` bytes, or null when `context_len` is 0.
 * `include_all` and `out_len` must be null or valid for the call.
 */
const uint8_t *resolve_all(void *engine_ptr,
                           const uint8_t *context_data,
                           const bool *include_all,
                           uintptr_t context_len,
                           uintptr_t *out_len);

/**
 * Evaluates a single toggle by name.
 *
 * On success returns an `EvaluatedToggle` protobuf and writes its length to
 * `out_len`; the buffer must be released with [`free_rust_buffer`]. On failure
 * — including when no such toggle is known — returns null and writes `0`.
 *
 * # Safety
 * `engine_ptr` must be null or from [`new_engine`]. `toggle_name_ptr` must be
 * null or a valid C string. `context_data` must be readable for `context_len`
 * bytes, or null when `context_len` is 0. `out_len` must be null or valid.
 */
const uint8_t *resolve(void *engine_ptr,
                       const char *toggle_name_ptr,
                       const uint8_t *context_data,
                       uintptr_t context_len,
                       uintptr_t *out_len);

/**
 * Returns whether a toggle is enabled, failing closed: any error, unknown
 * toggle, or missing state yields `false`.
 *
 * # Safety
 * `engine_ptr` must be null or from [`new_engine`]. `toggle_name_ptr` must be
 * null or a valid C string. `context_data` must be readable for `context_len`
 * bytes, or null when `context_len` is 0.
 */
bool is_enabled(void *engine_ptr,
                const char *toggle_name_ptr,
                const uint8_t *context_data,
                uintptr_t context_len);

/**
 * Releases a buffer returned by [`resolve`] or [`resolve_all`].
 *
 * # Safety
 * `ptr`/`len` must be a pair produced by [`resolve`] or [`resolve_all`] and not
 * yet freed, or `ptr` must be null.
 */
void free_rust_buffer(uint8_t *ptr, uintptr_t len);

/**
 * Releases a response returned by [`take_state`].
 *
 * # Safety
 * `response_ptr` must be null or a pointer from [`take_state`] that has not
 * already been freed.
 */
void free_response(char *response_ptr);

#endif  /* FRONTEND_ENGINE_H */
