// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: toggles.proto

package unleashengine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariantPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantPayload) Reset() {
	*x = VariantPayload{}
	mi := &file_toggles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantPayload) ProtoMessage() {}

func (x *VariantPayload) ProtoReflect() protoreflect.Message {
	mi := &file_toggles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantPayload.ProtoReflect.Descriptor instead.
func (*VariantPayload) Descriptor() ([]byte, []int) {
	return file_toggles_proto_rawDescGZIP(), []int{0}
}

func (x *VariantPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VariantPayload) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EvaluatedVariant struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Enabled           bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled"`
	Payload           *VariantPayload        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload"`
	FeatureEnabled    bool                   `protobuf:"varint,4,opt,name=feature_enabled,json=featureEnabled,proto3" json:"feature_enabled"`
	OldFeatureEnabled bool                   `protobuf:"varint,5,opt,name=old_feature_enabled,json=oldFeatureEnabled,proto3" json:"featureEnabled"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EvaluatedVariant) Reset() {
	*x = EvaluatedVariant{}
	mi := &file_toggles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatedVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatedVariant) ProtoMessage() {}

func (x *EvaluatedVariant) ProtoReflect() protoreflect.Message {
	mi := &file_toggles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatedVariant.ProtoReflect.Descriptor instead.
func (*EvaluatedVariant) Descriptor() ([]byte, []int) {
	return file_toggles_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluatedVariant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EvaluatedVariant) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EvaluatedVariant) GetPayload() *VariantPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EvaluatedVariant) GetFeatureEnabled() bool {
	if x != nil {
		return x.FeatureEnabled
	}
	return false
}

func (x *EvaluatedVariant) GetOldFeatureEnabled() bool {
	if x != nil {
		return x.OldFeatureEnabled
	}
	return false
}

type EvaluatedToggle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Enabled        bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled"`
	Variant        *EvaluatedVariant      `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant"`
	ImpressionData bool                   `protobuf:"varint,4,opt,name=impression_data,json=impressionData,proto3" json:"impressionData"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluatedToggle) Reset() {
	*x = EvaluatedToggle{}
	mi := &file_toggles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatedToggle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatedToggle) ProtoMessage() {}

func (x *EvaluatedToggle) ProtoReflect() protoreflect.Message {
	mi := &file_toggles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatedToggle.ProtoReflect.Descriptor instead.
func (*EvaluatedToggle) Descriptor() ([]byte, []int) {
	return file_toggles_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluatedToggle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EvaluatedToggle) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EvaluatedToggle) GetVariant() *EvaluatedVariant {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *EvaluatedToggle) GetImpressionData() bool {
	if x != nil {
		return x.ImpressionData
	}
	return false
}

type Variant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Enabled        bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled"`
	FeatureEnabled bool                   `protobuf:"varint,3,opt,name=feature_enabled,json=featureEnabled,proto3" json:"feature_enabled"`
	Payload        *VariantPayload        `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_toggles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_toggles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_toggles_proto_rawDescGZIP(), []int{3}
}

func (x *Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variant) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Variant) GetFeatureEnabled() bool {
	if x != nil {
		return x.FeatureEnabled
	}
	return false
}

func (x *Variant) GetPayload() *VariantPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ResolvedToggle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Project        string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Variant        *Variant               `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	ImpressionData bool                   `protobuf:"varint,4,opt,name=impression_data,json=impressionData,proto3" json:"impression_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvedToggle) Reset() {
	*x = ResolvedToggle{}
	mi := &file_toggles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedToggle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedToggle) ProtoMessage() {}

func (x *ResolvedToggle) ProtoReflect() protoreflect.Message {
	mi := &file_toggles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedToggle.ProtoReflect.Descriptor instead.
func (*ResolvedToggle) Descriptor() ([]byte, []int) {
	return file_toggles_proto_rawDescGZIP(), []int{4}
}

func (x *ResolvedToggle) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ResolvedToggle) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ResolvedToggle) GetVariant() *Variant {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *ResolvedToggle) GetImpressionData() bool {
	if x != nil {
		return x.ImpressionData
	}
	return false
}

type EvaluatedToggleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Toggles       []*EvaluatedToggle     `protobuf:"bytes,1,rep,name=toggles,proto3" json:"toggles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatedToggleList) Reset() {
	*x = EvaluatedToggleList{}
	mi := &file_toggles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatedToggleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatedToggleList) ProtoMessage() {}

func (x *EvaluatedToggleList) ProtoReflect() protoreflect.Message {
	mi := &file_toggles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatedToggleList.ProtoReflect.Descriptor instead.
func (*EvaluatedToggleList) Descriptor() ([]byte, []int) {
	return file_toggles_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluatedToggleList) GetToggles() []*EvaluatedToggle {
	if x != nil {
		return x.Toggles
	}
	return nil
}

var File_toggles_proto protoreflect.FileDescriptor

const file_toggles_proto_rawDesc = "" +
	"\n" +
	"\rtoggles.proto\x12\runleashengine\":\n" +
	"\x0eVariantPayload\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xd2\x01\n" +
	"\x10EvaluatedVariant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x127\n" +
	"\apayload\x18\x03 \x01(\v2\x1d.unleashengine.VariantPayloadR\apayload\x12'\n" +
	"\x0ffeature_enabled\x18\x04 \x01(\bR\x0efeatureEnabled\x12.\n" +
	"\x13old_feature_enabled\x18\x05 \x01(\bR\x11oldFeatureEnabled\"\xa3\x01\n" +
	"\x0fEvaluatedToggle\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x129\n" +
	"\avariant\x18\x03 \x01(\v2\x1f.unleashengine.EvaluatedVariantR\avariant\x12'\n" +
	"\x0fimpression_data\x18\x04 \x01(\bR\x0eimpressionData\"\x99\x01\n" +
	"\aVariant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12'\n" +
	"\x0ffeature_enabled\x18\x03 \x01(\bR\x0efeatureEnabled\x127\n" +
	"\apayload\x18\x04 \x01(\v2\x1d.unleashengine.VariantPayloadR\apayload\"\x9f\x01\n" +
	"\x0eResolvedToggle\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x120\n" +
	"\avariant\x18\x03 \x01(\v2\x16.unleashengine.VariantR\avariant\x12'\n" +
	"\x0fimpression_data\x18\x04 \x01(\bR\x0eimpressionData\"O\n" +
	"\x13EvaluatedToggleList\x128\n" +
	"\atoggles\x18\x01 \x03(\v2\x1e.unleashengine.EvaluatedToggleR\atogglesB\x11Z\x0f./unleashengineb\x06proto3"

var (
	file_toggles_proto_rawDescOnce sync.Once
	file_toggles_proto_rawDescData []byte
)

func file_toggles_proto_rawDescGZIP() []byte {
	file_toggles_proto_rawDescOnce.Do(func() {
		file_toggles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_toggles_proto_rawDesc), len(file_toggles_proto_rawDesc)))
	})
	return file_toggles_proto_rawDescData
}

var file_toggles_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_toggles_proto_goTypes = []any{
	(*VariantPayload)(nil),      // 0: unleashengine.VariantPayload
	(*EvaluatedVariant)(nil),    // 1: unleashengine.EvaluatedVariant
	(*EvaluatedToggle)(nil),     // 2: unleashengine.EvaluatedToggle
	(*Variant)(nil),             // 3: unleashengine.Variant
	(*ResolvedToggle)(nil),      // 4: unleashengine.ResolvedToggle
	(*EvaluatedToggleList)(nil), // 5: unleashengine.EvaluatedToggleList
}
var file_toggles_proto_depIdxs = []int32{
	0, // 0: unleashengine.EvaluatedVariant.payload:type_name -> unleashengine.VariantPayload
	1, // 1: unleashengine.EvaluatedToggle.variant:type_name -> unleashengine.EvaluatedVariant
	0, // 2: unleashengine.Variant.payload:type_name -> unleashengine.VariantPayload
	3, // 3: unleashengine.ResolvedToggle.variant:type_name -> unleashengine.Variant
	2, // 4: unleashengine.EvaluatedToggleList.toggles:type_name -> unleashengine.EvaluatedToggle
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_toggles_proto_init() }
func file_toggles_proto_init() {
	if File_toggles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_toggles_proto_rawDesc), len(file_toggles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toggles_proto_goTypes,
		DependencyIndexes: file_toggles_proto_depIdxs,
		MessageInfos:      file_toggles_proto_msgTypes,
	}.Build()
	File_toggles_proto = out.File
	file_toggles_proto_goTypes = nil
	file_toggles_proto_depIdxs = nil
}
